"""Creating posts

Revision ID: 701f18a871cf
Revises: a20022e1f319
Create Date: 2019-07-21 21:41:12.540589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701f18a871cf'
down_revision = 'a20022e1f319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=1028), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
